### ISSUE TITLE
提个小小建议

### ISSUE THREAD

**Issue by jason-liu475** [HammCn/BBBUG_Frontend#1]
上传本地歌曲后，模态框没有关闭按钮，点旁边就关闭了，还要重新上传一遍

**Comment by HammCn** [comment]
感谢反馈，模态框UI正在调整，欢迎继续关注！

**Comment by HammCn** [comment]
已优化这个问题 https://github.com/HammCn/BBBUG_Frontend/commit/ac0a4b80669a6aee678be5a2084f96b1edadfd45
