### ISSUE TITLE
Bug？

### ISSUE THREAD

**Issue by zhuwenbing** [HammCn/BBBUG_Frontend#2]
浏览器一直不停请求各种图片地址，如图
![image](https://user-images.githubusercontent.com/12619096/113378430-96947580-93a9-11eb-8a37-66a77cc98d8e.png)

**Comment by zhuwenbing** [comment]
无法复现，关闭issue

**Comment by HammCn** [comment]
这是歌曲的封面头图，每首歌播放的时候就会加载。

**Comment by zhuwenbing** [comment]
> 这是歌曲的封面头图，每首歌播放的时候就会加载。

了解。不过请求超过上万次后，仍然没有停下来的迹象，而且歌单里也只有一两首歌而已。

**Comment by zhuwenbing** [comment]
刚刚复现出来了：打开“已点”之后就会一直请求封面图片地址，而且没有要停下来的迹象。如下图
![image](https://user-images.githubusercontent.com/12619096/113384328-61435400-93b8-11eb-9f51-cbfef51a8d9a.png)
截止截图完成已发送7927次请求，数据传输量266MB。

**Comment by HammCn** [comment]
方便的话提供几个请求的图片URL地址我追一下问题

**Comment by zhuwenbing** [comment]
https://img1.kuwo.cn/star/albumcover/500/80/41/2314081861.jpg
https://img1.kuwo.cn/star/albumcover/500/53/32/1379441173.jpg
https://img3.kuwo.cn/star/albumcover/300/48/47/309391875.jpg
这个问题貌似在有歌曲封面的地方都会出现。比如在“点歌”--“歌曲搜索”中搜索出歌曲后就会不停请求这些歌曲的封面图片地址。

**Comment by HammCn** [comment]
已多次测试，暂未发现这个问题，如果下次碰到可以提供一下console和network部分的截图，谢谢

**Comment by zhuwenbing** [comment]
录了段屏传上来，希望有用吧。
[Video_20210407105653.zip](https://github.com/HammCn/BBBUG_Frontend/files/6268726/Video_20210407105653.zip)

**Comment by HammCn** [comment]
问题已复现，关闭 NetWork下的Disable Caches即可。
