### ISSUE TITLE
页面经常 CPU 占用 100%

### ISSUE THREAD

**Issue by jinliming2** [HammCn/BBBUG_Frontend#6]
浏览器：Chrome Canary
系统：Windows、Mac 都存在

进入首页，~~点几 首歌，听一会~~ 直接打开“已点”，系统进程管理就能看到 Chrome 的 CPU 高占用，进浏览器右上角菜单-More Tools-Task Manager可以看到是这个标签页的问题。

复现概率很高。

![image](https://user-images.githubusercontent.com/10294977/120927771-9fd8f000-c714-11eb-98c3-b3911c7d0c06.png)

![GIF](https://user-images.githubusercontent.com/10294977/120928713-64d8bb80-c718-11eb-859c-5a9d4337a6a1.gif)

![image](https://user-images.githubusercontent.com/10294977/120928735-7fab3000-c718-11eb-9c7e-8e520802555a.png)

可以看到性能监控里，时间基本上被 Microtasks 打满，开始出现丢帧。

**Comment by HammCn** [comment]
问题已知，下个版本修复

**Comment by HammCn** [comment]
已修复。
